-- run this before running any dags
CREATE OR REPLACE STAGE ARTISTS_STAGE;
CREATE OR REPLACE STAGE LISTENING_RECORDS_STAGE;
CREATE OR REPLACE STAGE GENRES_STAGE;
CREATE OR REPLACE STAGE SONGS_INCOMPLETE_STAGE;
CREATE OR REPLACE STAGE EXPANDED_SONG_DATASET_STAGE;