CREATE OR REPLACE TABLE SONGS AS
SELECT
    expanded.TRACK_ID AS SONG_ID,
    expanded.TRACK_NAME AS SONG_NAME,
    COALESCE(s.ARTIST_ID, a.ARTIST_ID) AS ARTIST_ID,
    expanded.ALBUM,
    expanded.ALBUM_ID,
    expanded.DURATION_MS,
    expanded.EXPLICIT,
    expanded.POPULARITY,
    expanded.RELEASE_DATE,
    CASE
        WHEN s.SONG_ID IS NOT NULL THEN TRUE
        ELSE FALSE
    END AS IS_LISTENED_BEFORE
FROM EXPANDED_SONG_DATASET expanded
LEFT JOIN SONGS_INCOMPLETE s ON expanded.TRACK_ID = s.SONG_ID
LEFT JOIN ARTISTS a ON UPPER(TRIM(expanded.ARTIST)) = UPPER(TRIM(a.ARTIST_NAME));